### ISSUE TITLE
Website not avaible!

### ISSUE THREAD

**Issue by drmatoi** [JonnycatMeow/Jcports#16]
I wanted to check your site!  I get this error: Site Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on Netlify.

[Back to our site](https://jonnycatports.netlify.app/)

If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's ["page not found" support guide](https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125?utm_source=404page&utm_campaign=community_tracking) for troubleshooting tips.

Netlify Internal ID: 01GW57VVAZEA43X40J5ZPBCJJ9

Please fix this :D Also I am a reverse android developer! Want to work together? Write me on Telegram! t.me/mrmatoi

**Comment by JonnycatMeow** [comment]
oh hi yes here is the website https://jcports.netlify.app/

**Comment by JonnycatMeow** [comment]
and uhh the stuff i do is friday night funkin mod related stuff so it uses haxe so idk if you can help me but you can if you want to. i have wanted to add android support anyways
